services:
  scraper:
    build: .
    container_name: banorte_scraper
    ports:
      - "8000:8000"  # <--- Esto expone el puerto
    environment:
      - .env
    volumes:
      - ./main.py:/app/main.py
    restart: unless-stopped